[build]
  builder = "nixpacks"
  buildCommand = "npm install"
  startCommand = "node server.js"

[deploy]
  startCommand = "node server.js"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartDelay = 5
  restartMax = 3
  restartTimeout = 60

[variables]
  PORT = "3001"
  NODE_ENV = "production"
  PLAYWRIGHT_BROWSERS_PATH = "0"  # This will use the bundled browser

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[buildpacks]
  nodejs = {}
  nixpacks = {}

[buildpacks.nodejs]
  node-version = "18"

[buildpacks.nixpacks]
  nixpacks-version = "latest"
